Llvm-backend update with Master
Quansight-Labs/taco pull request #1
Opened 2021-05-23 02:25 UTC by Robertorosmaninho

2021-05-25 14:23 UTC, guilhermeleobas requested changes
I suppose you commit with merge conflicts. And might be other conflicts as well

2021-05-25 14:23 UTC, guilhermeleobas commented on CMakeLists.txt
> +>>>>>>> master
I suppose this shouldn't be here

2021-05-25 15:24 UTC, Robertorosmaninho commented on CMakeLists.txt
> +>>>>>>> master
fixed

2021-05-26 19:26 UTC, guilhermeleobas commented
Hi Roberto, can you fix the conflict? Also, to make sure the merge is working, can you build taco without LLVM and run the tests?

```bash
cmake path/to/taco -DLLVM=OFF 
make 
make test
```

2021-05-26 20:12 UTC, Robertorosmaninho commented
> Hi Roberto, can you fix the conflict? Also, to make sure the merge is working, can you build taco without LLVM and run the tests?
> 
> ```shell
> cd path/to/taco
> mkdir build
> cd build
> cmake -DLLVM=OFF ..
> make -j4
> make test
> ```

I got the following error (with and without LLVM):
```
make
[  0%] Building CXX object src/CMakeFiles/taco.dir/cuda.cpp.o
[  1%] Building CXX object src/CMakeFiles/taco.dir/error.cpp.o
[  2%] Building CXX object src/CMakeFiles/taco.dir/format.cpp.o
[  3%] Building CXX object src/CMakeFiles/taco.dir/ir_tags.cpp.o
[  4%] Building CXX object src/CMakeFiles/taco.dir/llvm.cpp.o
[  5%] Building CXX object src/CMakeFiles/taco.dir/taco_tensor_t.cpp.o
[  6%] Building CXX object src/CMakeFiles/taco.dir/target.cpp.o
[  7%] Building CXX object src/CMakeFiles/taco.dir/tensor.cpp.o
[  8%] Building CXX object src/CMakeFiles/taco.dir/type.cpp.o
[  9%] Building CXX object src/CMakeFiles/taco.dir/codegen/codegen.cpp.o
[ 10%] Building CXX object src/CMakeFiles/taco.dir/codegen/codegen_c.cpp.o
[ 11%] Building CXX object src/CMakeFiles/taco.dir/codegen/codegen_cuda.cpp.o
[ 12%] Building CXX object src/CMakeFiles/taco.dir/codegen/codegen_llvm.cpp.o
In file included from /Users/robertorosmaninho/taco/src/codegen/codegen_llvm.cpp:4:
/Users/robertorosmaninho/taco/src/codegen/codegen_llvm.h:27:18: warning: private field 'outputKind' is not used [-Wunused-private-field]
      OutputKind outputKind;
                 ^
1 warning generated.
[ 13%] Building CXX object src/CMakeFiles/taco.dir/codegen/module.cpp.o
[ 14%] Building CXX object src/CMakeFiles/taco.dir/error/error_checks.cpp.o
[ 15%] Building CXX object src/CMakeFiles/taco.dir/error/error_messages.cpp.o
[ 16%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation.cpp.o
[ 17%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation_nodes.cpp.o
[ 18%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation_nodes_abstract.cpp.o
[ 19%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation_printer.cpp.o
[ 20%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation_rewriter.cpp.o
[ 21%] Building CXX object src/CMakeFiles/taco.dir/index_notation/index_notation_visitor.cpp.o
[ 22%] Building CXX object src/CMakeFiles/taco.dir/index_notation/intrinsic.cpp.o
[ 23%] Building CXX object src/CMakeFiles/taco.dir/index_notation/kernel.cpp.o
[ 24%] Building CXX object src/CMakeFiles/taco.dir/index_notation/provenance_graph.cpp.o
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1066:23: warning: loop variable 'parent' creates a copy from type 'const taco::IndexVar' [-Wrange-loop-construct]
  for (const IndexVar parent : getParents(indexVar)) {
                      ^
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1066:8: note: use reference type 'const taco::IndexVar &' to prevent copying
  for (const IndexVar parent : getParents(indexVar)) {
       ^~~~~~~~~~~~~~~~~~~~~~~
                      &
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1086:23: warning: loop variable 'parent' creates a copy from type 'const taco::IndexVar' [-Wrange-loop-construct]
  for (const IndexVar parent : getParents(indexVar)) {
                      ^
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1086:8: note: use reference type 'const taco::IndexVar &' to prevent copying
  for (const IndexVar parent : getParents(indexVar)) {
       ^~~~~~~~~~~~~~~~~~~~~~~
                      &
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1102:23: warning: loop variable 'parent' creates a copy from type 'const taco::IndexVar' [-Wrange-loop-construct]
  for (const IndexVar parent : getParents(indexVar)) {
                      ^
/Users/robertorosmaninho/taco/src/index_notation/provenance_graph.cpp:1102:8: note: use reference type 'const taco::IndexVar &' to prevent copying
  for (const IndexVar parent : getParents(indexVar)) {
       ^~~~~~~~~~~~~~~~~~~~~~~
                      &
3 warnings generated.
[ 25%] Building CXX object src/CMakeFiles/taco.dir/index_notation/schedule.cpp.o
[ 26%] Building CXX object src/CMakeFiles/taco.dir/index_notation/transformations.cpp.o
[ 27%] Building CXX object src/CMakeFiles/taco.dir/ir/ir.cpp.o
[ 28%] Building CXX object src/CMakeFiles/taco.dir/ir/ir_generators.cpp.o
[ 29%] Building CXX object src/CMakeFiles/taco.dir/ir/ir_printer.cpp.o
[ 30%] Building CXX object src/CMakeFiles/taco.dir/ir/ir_rewriter.cpp.o
[ 31%] Building CXX object src/CMakeFiles/taco.dir/ir/ir_verifier.cpp.o
[ 32%] Building CXX object src/CMakeFiles/taco.dir/ir/ir_visitor.cpp.o
[ 33%] Building CXX object src/CMakeFiles/taco.dir/ir/simplify.cpp.o
[ 34%] Building CXX object src/CMakeFiles/taco.dir/lower/expr_tools.cpp.o
[ 35%] Building CXX object src/CMakeFiles/taco.dir/lower/iteration_forest.cpp.o
[ 36%] Building CXX object src/CMakeFiles/taco.dir/lower/iteration_graph.cpp.o
[ 37%] Building CXX object src/CMakeFiles/taco.dir/lower/iterator.cpp.o
[ 38%] Building CXX object src/CMakeFiles/taco.dir/lower/lower.cpp.o
[ 39%] Building CXX object src/CMakeFiles/taco.dir/lower/lowerer_impl.cpp.o
/Users/robertorosmaninho/taco/src/lower/lowerer_impl.cpp:143:23: warning: loop variable 'indexVar' creates a copy from type 'const taco::IndexVar' [-Wrange-loop-construct]
  for (const IndexVar indexVar : provGraph.getAllIndexVars()) {
                      ^
/Users/robertorosmaninho/taco/src/lower/lowerer_impl.cpp:143:8: note: use reference type 'const taco::IndexVar &' to prevent copying
  for (const IndexVar indexVar : provGraph.getAllIndexVars()) {
       ^~~~~~~~~~~~~~~~~~~~~~~~~
                      &
1 warning generated.
[ 40%] Building CXX object src/CMakeFiles/taco.dir/lower/merge_lattice.cpp.o
[ 41%] Building CXX object src/CMakeFiles/taco.dir/lower/mode.cpp.o
[ 42%] Building CXX object src/CMakeFiles/taco.dir/lower/mode_access.cpp.o
[ 43%] Building CXX object src/CMakeFiles/taco.dir/lower/mode_format_compressed.cpp.o
[ 44%] Building CXX object src/CMakeFiles/taco.dir/lower/mode_format_dense.cpp.o
[ 45%] Building CXX object src/CMakeFiles/taco.dir/lower/mode_format_impl.cpp.o
[ 46%] Building CXX object src/CMakeFiles/taco.dir/lower/mode_format_singleton.cpp.o
[ 47%] Building CXX object src/CMakeFiles/taco.dir/lower/tensor_path.cpp.o
[ 48%] Building CXX object src/CMakeFiles/taco.dir/parser/einsum_parser.cpp.o
[ 49%] Building CXX object src/CMakeFiles/taco.dir/parser/lexer.cpp.o
[ 50%] Building CXX object src/CMakeFiles/taco.dir/parser/parser.cpp.o
[ 51%] Building CXX object src/CMakeFiles/taco.dir/storage/array.cpp.o
[ 52%] Building CXX object src/CMakeFiles/taco.dir/storage/file_io_mtx.cpp.o
[ 53%] Building CXX object src/CMakeFiles/taco.dir/storage/file_io_rb.cpp.o
[ 54%] Building CXX object src/CMakeFiles/taco.dir/storage/file_io_tns.cpp.o
[ 55%] Building CXX object src/CMakeFiles/taco.dir/storage/index.cpp.o
[ 56%] Building CXX object src/CMakeFiles/taco.dir/storage/pack.cpp.o
[ 57%] Building CXX object src/CMakeFiles/taco.dir/storage/storage.cpp.o
[ 58%] Building CXX object src/CMakeFiles/taco.dir/storage/typed_index.cpp.o
[ 59%] Building CXX object src/CMakeFiles/taco.dir/storage/typed_value.cpp.o
[ 60%] Building CXX object src/CMakeFiles/taco.dir/util/env.cpp.o
[ 61%] Building CXX object src/CMakeFiles/taco.dir/util/files.cpp.o
[ 62%] Building CXX object src/CMakeFiles/taco.dir/util/name_generator.cpp.o
[ 63%] Building CXX object src/CMakeFiles/taco.dir/util/strings.cpp.o
[ 64%] Linking CXX shared library ../lib/libtaco.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
  "llvm::AllocaInst::AllocaInst(llvm::Type*, unsigned int, llvm::Value*, llvm::Align, llvm::Twine const&, llvm::Instruction*)", referenced from:
      llvm::IRBuilderBase::CreateAlloca(llvm::Type*, llvm::Value*, llvm::Twine const&) in codegen_llvm.cpp.o
  "llvm::BasicBlock::BasicBl [...]

2021-05-27 00:25 UTC, Robertorosmaninho commented
> Hi Roberto, can you fix the conflict? Also, to make sure the merge is working, can you build taco without LLVM and run the tests?
> 
> ```shell
> cd path/to/taco
> mkdir build
> cd build
> cmake -DLLVM=OFF ..
> make -j4
> make test
> ```

Here is the output:
```
$ make test
Running tests...
Test project /home/vagrant/taco/build_noLLVM
        Start   1: */apiset.api/*
  1/190 Test   #1: */apiset.api/* .................................   Passed    0.98 sec
        Start   2: */apiget.api/*
  2/190 Test   #2: */apiget.api/* .................................   Passed    0.35 sec
        Start   3: */apiwrb.api/*
  3/190 Test   #3: */apiwrb.api/* .................................   Passed    0.35 sec
        Start   4: */apiwmtx.api/*
  4/190 Test   #4: */apiwmtx.api/* ................................   Passed    0.47 sec
        Start   5: */apitns.api/*
  5/190 Test   #5: */apitns.api/* .................................   Passed    0.60 sec
        Start   6: expr.simplify_copy
  6/190 Test   #6: expr.simplify_copy .............................   Passed    0.34 sec
        Start   7: expr.simplify_copy_before_update
  7/190 Test   #7: expr.simplify_copy_before_update ...............   Passed    0.33 sec
        Start   8: expr.simplify_dont_copy_loop_dependent_var
  8/190 Test   #8: expr.simplify_dont_copy_loop_dependent_var .....   Passed    0.32 sec
        Start   9: error.expr_dimension_mismatch_freevar
  9/190 Test   #9: error.expr_dimension_mismatch_freevar ..........   Passed    0.34 sec
        Start  10: error.expr_dimension_mismatch_sumvar
 10/190 Test  #10: error.expr_dimension_mismatch_sumvar ...........   Passed    0.34 sec
        Start  11: error.compile_without_expr
 11/190 Test  #11: error.compile_without_expr .....................   Passed    0.33 sec
        Start  12: error.compile_tensor_name_collision
 12/190 Test  #12: error.compile_tensor_name_collision ............   Passed    0.32 sec
        Start  13: error.assemble_without_compile
 13/190 Test  #13: error.assemble_without_compile .................   Passed    0.32 sec
        Start  14: error.compute_without_compile
 14/190 Test  #14: error.compute_without_compile ..................   Passed    0.31 sec
        Start  15: expr.reduction0
 15/190 Test  #15: expr.reduction0 ................................   Passed    0.69 sec
        Start  16: expr.repeated_operand
 16/190 Test  #16: expr.repeated_operand ..........................   Passed    0.57 sec
        Start  17: expr.accumulate
 17/190 Test  #17: expr.accumulate ................................***Not Run (Disabled)   0.00 sec
        Start  18: expr.sub
 18/190 Test  #18: expr.sub .......................................   Passed    0.69 sec
        Start  19: expr.simplify_neg
 19/190 Test  #19: expr.simplify_neg ..............................   Passed    0.32 sec
        Start  20: expr.simplify_elmul
 20/190 Test  #20: expr.simplify_elmul ............................   Passed    0.32 sec
        Start  21: expr.simplify_add
 21/190 Test  #21: expr.simplify_add ..............................   Passed    0.32 sec
        Start  22: expr.simplify_addmul
 22/190 Test  #22: expr.simplify_addmul ...........................   Passed    0.33 sec
        Start  23: expr.simplify_muladd
 23/190 Test  #23: expr.simplify_muladd ...........................   Passed    0.33 sec
        Start  24: expr.scalarops
 24/190 Test  #24: expr.scalarops .................................   Passed    0.32 sec
        Start  25: expr.redefine
 25/190 Test  #25: expr.redefine ..................................   Passed    0.64 sec
        Start  26: */expr.storage/*
 26/190 Test  #26: */expr.storage/* ...............................   Passed   12.67 sec
        Start  27: format.mm_permute_formats
 27/190 Test  #27: format.mm_permute_formats ......................***Not Run (Disabled)   0.00 sec
        Start  28: */format.pack/*
 28/190 Test  #28: */format.pack/* ................................   Passed    9.32 sec
        Start  29: format.sparse
 29/190 Test  #29: format.sparse ..................................   Passed    0.47 sec
        Start  30: format.dense
 30/190 Test  #30: format.dense ...................................   Passed    0.47 sec
        Start  31: index.size
 31/190 Test  #31: index.size .....................................   Passed    0.32 sec
        Start  32: index.makeCSR
 32/190 Test  #32: index.makeCSR ..................................   Passed    0.32 sec
        Start  33: notation.isEinsumNotation
 33/190 Test  #33: notation.isEinsumNotation ......................   Passed    0.33 sec
        Start  34: notation.isReductionNotation
 34/190 Test  #34: notation.isReductionNotation ...................   Passed    0.32 sec
        Start  35: notation.isConcreteNotation
 35/190 Test  #35: notation.isConcreteNotation ....................   Passed    0.34 sec
        Start  36: notation.makeReductionNotation
 36/190 Test  #36: notation.makeReductionNotation .................   Passed    0.33 sec
        Start  37: notation.isomorphic
 37/190 Test  #37: notation.isomorphic ............................   Passed    0.32 sec
        Start  38: notation.generatePackCOOStmt
 38/190 Test  #38: notation.generatePackCOOStmt ...................   Passed    0.31 sec
        Start  39: */concrete.notation/*
 39/190 Test  #39: */concrete.notation/* ..........................   Passed    0.34 sec
        Start  40: indexexpr.access
 40/190 Test  #40: indexexpr.access ...............................   Passed    0.33 sec
        Start  41: indexexpr.literal
 41/190 Test  #41: indexexpr.literal ..............................   Passed    0.33 sec
        Start  42: indexexpr.neg
 42/190 Test  #42: indexexpr.neg ..................................   Passed    0.32 sec
        Start  43: indexexpr.add
 43/190 Test  #43: indexexpr.add ..................................   Passed    0.34 sec
        Start  44: indexexpr.sub
 44/190 Test  #44: indexexpr.sub ..................................   Passed    0.32 sec
        Start  45: indexexpr.mul
 45/190 Test  #45: indexexpr.mul ..................................   Passed    0.32 sec
        Start  46: indexexpr.div
 46/190 Test  #46: indexexpr.div ..................................   Passed    0.32 sec
        Start  47: indexstmt.assignment
 47/190 Test  #47: indexstmt.assignment ...........................   Passed    0.33 sec
        Start  48: indexstmt.forall
 48/190 Test  #48: indexstmt.forall ...............................   Passed    0.32 sec
        Start  49: indexstmt.where
 49/190 Test  #49: indexstmt.where ................................   Passed    0.35 sec
        Start  50: indexstmt.multi
 50/190 Test  #50: indexstmt.multi ................................   Passed    0.32 sec
        Start  51: indexstmt.sequence
 51/190 Test  #51: indexstmt.sequence .............................   Passed    0.32 sec
        Start  52: indexstmt.spmm
 52/190 Test  #52: indexstmt.spmm .................................   Passed    0.35 sec
        Start  53: io.tns
 53/190 Test  #53: io.tns .........................................   Passed    0.49 sec
        Start  54: io.mtx
 54/190 Test  #54: io.mtx .........................................   Passed    0.48 sec
        Start  55: io.tensor
 55/190 Test  #55: io.tensor ......................................   Passed    0.49 sec
        Start  56: io.ttxdense
 56/190 Test  #56: io.ttxdense ....................................   Passed    0.48 sec
        Start  57: io.ttxsparse
 57/190 Test  #57: io.ttxsparse ...................................   Passed    0.49 sec
        Start  58: io.mtxsymmetric
 58/190 Test  #58: io.mtxsymmetric ................................   Passed    0.47 sec
        Start  59: */lower.compile/*
 59/190 Test  #59: */lower.compile/* ..............................   Passed   34.57 sec
        Start  60: */merge_lattice.test/*
 60/190 Test  #60: */merge_lattice.test/* .........................   Passed  [...]

2021-05-27 00:39 UTC, guilhermeleobas commented
Thanks, @Robertorosmaninho

2021-05-27 00:40 UTC, merged